### ISSUE TITLE
Problem with IE 8

### ISSUE THREAD

**Issue by jolline** [kenwheeler/slick#1209]
I having this error appearing in the console: Object doesn't support property or method 'bind'.

It works fine with other later versions of IE. These are my code:

$(document).ready(function() {
     $('.slider-for').slick({
	  slidesToShow: 1,
	  slidesToScroll: 1,
	  arrows: false,
	  fade: true,
	  asNavFor: '.slider-nav'
	});
	$('.slider-nav').slick({
	  slidesToShow: 3,
	  slidesToScroll: 1,
	  asNavFor: '.slider-for',
	  dots: false,
	  centerMode: true,
	  focusOnSelect: true
	});
});

< div class="slider-for" >
	< div>1< /div>
	< div>2< /div>
	< div>3< /div>
	< div>4< /div>
< /div>

< div class="slider-nav" >
	< div>1< /div>
	< div>4< /div>
	< div>5< /div>
	< div>2< /div>
< /div >

Any solution? Thank you

**Comment by luzat** [comment]
Just a wild guess: Are you using jQuery 2.x, which only supports IE 9+?

**Comment by simeydotme** [comment]
yeh, a JS Fiddle would help us, here.

**Comment by jolline** [comment]
i am using jquery v1.7.2 but according to the website, it supports 1.7 and above. 

Sorry, the fiddle is here: https://jsfiddle.net/eo6s8hbe/

I can't get the slick.js to load in properly though. Thank you for any help.

**Comment by simeydotme** [comment]
I don't have IE8 to test by right now, but is this one working as you expect?
I can look in IE8 later.

http://jsfiddle.net/s3fus170/

**Comment by jolline** [comment]
SCRIPT438: Object doesn't support property or method 'bind'
File: slick.min.js, Line: 19, Column: 17977

The error is still in.

**Comment by Ghostavio** [comment]
Have anyone looked into this, I'm having a similar issue, slick is not initializing but is not throwing any erros.

**Comment by wellic** [comment]
I added the polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill

And now I have no errors.
But is a crutch

**Comment by LdyMox** [comment]
I have a similar error in IE8, work on newer browsers. Most recent slick, Jquery 1.7.1 (also tried 1.9.1), works on IE11 but not on IE8. Stacks my slides rather then putting them side to side. Adding the Polyfil does not seem to help. 

  Object doesn't support this property or method  slick.min.js, line 19 character 17509

**Comment by LdyMox** [comment]
Playing around I can see the issue happens when I have any type of link in the slide. Only gives me issues in Ie8.

**Comment by LdyMox** [comment]
The solution I came up with was to remove any href HTML links, AKA simple HTML links and had to use javascript onmouse down action that then opened the link for me.

**Comment by Rido** [comment]
I got the same issue. I've put my code on JS Fiddle: http://jsfiddle.net/RidoNL/fLpxx0cd/3/
If you've changed the IE browser mode to IE 7 or 8 you get the following errors.

```
SCRIPT438: Object doesn't support property or method 'bind'
File: slick.min.js, Line: 19, Column: 17977
```

**Comment by kenwheeler** [comment]
Fixed on master, sorry guys

**Comment by Ghostavio** [comment]
Thanks, will update here

**Comment by entozoon** [comment]
I had a very similar IE8 issue, turns out it only exists on the (older) version downloaded from
http://kenwheeler.github.io/slick/#go-get-it

.. might be worth updating :)

**Comment by SimonHarte** [comment]
We have slick version 1.5.5 in our project and are still getting this error. We're using jQuery 1.11.2.

**Comment by anteksiler** [comment]
Who uses IE8 anyways, IE8 support should be dropped.

**Comment by entozoon** [comment]
That's not necessarily a valid opinion if you work for a web company.

**Comment by LdyMox** [comment]
Nearly 17% of computers are still windows XP and thus can only go up to IE 8 for IE anyways ( http://www.cnet.com/news/windows-xp-use-continues-to-drop-but-still-in-no-2-spot/ )

In my case I work for a smallish business and they have lots of older computers running about that still use WinXp

**Comment by kenwheeler** [comment]
IE8 unfortunately is still a player, so I choose to support it. Latest version should be fine, I've gotten so used to using an es5-shim that I let a .bind slide two releases back.

**Comment by anteksiler** [comment]
IE8 is only above 10% in China, other than that it's below < 5% in all other countries. Give me 1 good source that IE is above 10%.

http://gs.statcounter.com/#browser_version_partially_combined-ww-monthly-201406-201506

**Comment by kenwheeler** [comment]
hey @LdyMox if you go to line 1485 and replace `e` with `event` in the arguments and on the preventDefault, does this fix your issue with anchors?

**Comment by kenwheeler** [comment]
@anteksiler It's not that its above 10%, its that when you build websites that anyone gives a shit about, for example a multimillion dollar company, if 5% of their users can't shop their website, that translates to the high 6 figures of lost revenue. Sucks, but its reality.

**Comment by entozoon** [comment]
That, and also.. even if 0% of people use IE8, if your company's policy is to support it.. you have to support it.

**Comment by anteksiler** [comment]
@kenwheeler Reality won't change unless you do something about it :) If it weren't Apple, people would still be carrying Nokia's.

Like now, if you support IE8, people will be satisfied that they get the same experience in IE8, but if you don't, they will be forced to change it eventually.

@entozoon Your company will have to use a simpler website then?

**Comment by kenwheeler** [comment]
The reality is that corporate IT departments aren't upgrading their infrastructure. Another unfortunate reality is, that most companies care more about losing money than some random dude on the internet's opinion. I build applications for the biggest companies on the planet, and I can't remember a time that IE8 support wasn't a caveat.

**Comment by kenwheeler** [comment]
And don't get me wrong bruh, I'm with ya. If it was up to me I'd drop 9 and 10 support too, both pieces of shit as well. And Safari. lol.

**Comment by entozoon** [comment]
I'm entirely with you @kenwheeler !
But from the point of view of a small bespoke web company employee. Clients still want IE8 support!

**Comment by anteksiler** [comment]
I think we can agree to disagree, but do realize that as long as you support IE8, people won't put IE8 aside. Big companies can require it as much as they want, but if the script doesn't support it and man hours needed to make it work outweigh it's audience, they will change their attitude.

I know for a fact that Google dropped support for IE9:
http://googlesystem.blogspot.com.tr/2013/11/google-drops-support-for-ie9.html

Twitter dropped it for IE7 & IE8:
https://twittercommunity.com/t/update-on-twitter-for-websites-ie7-and-ie8-browser-support/28234

Microsoft already not supporting IE8.

**Comment by simeydotme** [comment]
Dropping support on your own website/platform/eco-system is a little different that dropping it in a plugin used by thousands of top-tier websites. Google/Twitter's web-apps have the perogative to choose who/what they support... both platforms are pretty much banned in China, anyway.
https://docs.angularjs.org/guide/ie
Also, this ^

It's a valid argument to drop support when the development cost outweighs the benefit and any fall-backs become inhibitive... but unless you're doing some really crazy shit, IE8 supports almost all the CSS needed for displaying a carousel (maybe not as sexily, but the fallbacks are fairly trivial) and jQuery does a damn fine job of patching in the javascript cutting your development costs.

**Comment by entozoon** [comment]
Hear hear!

**Comment by nominalaeon** [comment]
Related https://github.com/kenwheeler/slick/issues/1428#issuecomment-110072480

**Comment by Ghostavio** [comment]
you want a good reason, would you drop 5% of your revenue?

**Comment by alexeiTruhin** [comment]
had this problem with older version. 
updated script, now there are no errors in IE8. 
Thanks.
