### ISSUE TITLE
Responsive: Slides disappear on resize

### ISSUE THREAD

**Issue by Bigdragon13th** [kenwheeler/slick#2055]
I'm facing the same problem with this issue: https://github.com/kenwheeler/slick/issues/1995 which is already closed.

Here's the fiddle: https://jsfiddle.net/wL1t5qu8/

Step:
- Run the page on larger screen than breakpoint to see that there're 5 items and cannot autoplay because slidesToShow = 5. (correct)
- Resize the page to lower than breakpoint (768) to see that it show 3 items with autoplay. (correct)
- Wait for carousel to autoplay 1 item.
- Resize the page back to original size.
- The item showing is now 4 instead of 5 (bug)

Actually, if you wait for carousel to slide pass X items, when you resize back it's going to show 5 - X item. The only thing that's not reproduce this bug is when you wait carousel to slide pass exactly 5 items.

**Comment by leggomuhgreggo** [comment]
This isn't exactly elegant, but you can listen for the breakpoint/destroy events and do some resets as a work around.

[Here's a codepen](http://codepen.io/leggomuhgreggo/pen/bEajqd?editors=001)

**Comment by Bigdragon13th** [comment]
@leggomuhgreggo Thanks! That should do the trick for now.

**Comment by simeydotme** [comment]
This is due to `slidesToShow` being <= `slideCount` ... when it hits this condition, it needs to be resetting back to slide position 1.

**Comment by simeydotme** [comment]
I just pushed a fix to master for this.
You can download that from the repo, or wait for a release :+1: 
:bow:

**Comment by leggomuhgreggo** [comment]
@simeydotme Nice!

**Comment by simeydotme** [comment]
Oops, forgot to add the JSFiddle to show the fix;
http://jsfiddle.net/cz9ombo7/

**Comment by Bigdragon13th** [comment]
@simeydotme Thanks guy!

**Comment by DuudeXX8** [comment]
Guys this issue isn't solved look at this 

https://codepen.io/Onixia/pen/QrPaBP?editors=0110 

If you remove responsive part everything will be work great.But i need 1 slide in small screens Please help :(

**Comment by jaseel001** [comment]
@simeydotme What is the status of this fix in current version 1.8.1. This fix is works fine in version 1.5.9. But not working in 1.8.1(latest)

**Comment by DragosMocrii** [comment]
I confirm this is still happening

**Comment by tuffs** [comment]
This issue still occurs.

**Comment by Kazzje** [comment]
> Oops, forgot to add the JSFiddle to show the fix;
> http://jsfiddle.net/cz9ombo7/

Thanks @simeydotme! It works!!
