### ISSUE TITLE
Swiping triggers click, not always wanted

### ISSUE THREAD

**Issue by matthewlein** [kenwheeler/slick#764]
A change from 1.3.10 where you removed `return false` is giving me a behavior I don't want.

Swiping a video counts as a click and plays the video offscreen:
http://codepen.io/matthewlein/pen/miFJs

It could be the wistia.js code doing weird stuff, but 1.3.10 was perfect for me. Could this click behavior be opted in or out, or as an alternative the `return false`, could you instead use a custom event like `.trigger('slideClick.slick')` or something like that to give people a click hook?

**Comment by kenwheeler** [comment]
Fixed on dev

**Comment by kayzee** [comment]
Great work on this plugin @kenwheeler. I'm excited to test out the fix.  Does fixed on dev mean locally and not pushed to master?  I typically have a master and develop branch (git-flow) but I don't see any other branches in your repo.

**Comment by kenwheeler** [comment]
Its on master, but beware, there are some breaking changes so I dont recommend using it until I finish up the rest of 1.4 and document everything.

**Comment by kayzee** [comment]
No prob. Thanks again!

**Comment by tibineagu** [comment]
I believe this issue is still happening in 1.4. Please see fiddle http://jsfiddle.net/xxue5to9/
Thanks!

**Comment by kenwheeler** [comment]
So, a click event will fire from swipe. It won't click a link, but your click event will fire @tibineagu . So what would be the ideal resolution? A supressClick option or something?

**Comment by tibineagu** [comment]
Thanks for the reply. I would naturally assume click events should fire on click, not on drag (or more exactly when releasing after drag).
The current behaviour makes it almost impossible to build a carousel of items that trigger stuff on click (such as opening modals).

I think expected behaviour is to have the click events work on click (or tap), when the carousel is not moving or swiping. If current behaviour is to be preserved then I think an option that alters it slightly would be a good solution.

**Comment by kenwheeler** [comment]
I dont think this issue is native to slick. Try swipe clicking this:

http://jsfiddle.net/7un15ke8/

**Comment by tibineagu** [comment]
You're right, but in that context i don't think anyone expects to swipe-click on a static element.

I did build a workaround for supressing and unsupressing default click based on slick `beforeChange` and `afterChange` events, so my earlier observation can be ignored.

Thank you for getting involved and being so responsive, the plugin is tremendously helpful!

**Comment by phoenixMag00** [comment]
Hey @tibineagu, I'm running into the same issue with my lightboxes that are connected to images in the carousel. What's your workaround using beforeChange and afterChange look like?

**Comment by AQwebDev** [comment]
@phoenixMag00 
Did you get an answer to your question? I need the same fix as you needed. Can you help out?

**Comment by AQwebDev** [comment]
No action needed. Found a good solutions. Used that kind of event binding @mikerogerz mentioned in this issue: https://github.com/kenwheeler/slick/issues/1015

**Comment by andreibancioiu** [comment]
Code for the already described solution:

```
carousel.slick();

var isSliding = false;

carousel.on('beforeChange', function() {
    isSliding = true;
});

carousel.on('afterChange', function() {
    isSliding = false;
});

carousel.find(".foo").click(function() {
    if (isSliding) {
        return;
    }
    
    // ...
});
```
